server.modules += ( "mod_alias", "mod_cgi", "mod_setenv" )

$HTTP["url"] =~ "^/veci/" {
    alias.url = ( "/veci/" => "/www/veci/" )
    index-file.names = ( "index.html" )
}

$HTTP["url"] == "/ubus" {
    alias.url = ( "/ubus" => "/www/veci/ubus.cgi" )
    cgi.assign = ( ".cgi" => "" )
    setenv.add-environment = ( "PATH" => "/usr/bin:/usr/sbin:/bin:/sbin" )
}
